# Generated by Django 5.1.4 on 2024-12-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria de Paquetes', 'verbose_name_plural': 'Categorias de Paquetes'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
