# Generated by Django 5.1.4 on 2024-12-31 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0005_remove_cliente_cotizacion_remove_cotizacion_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flete',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='flete',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='flete',
            name='fecha_de_entrega',
        ),
        migrations.RemoveField(
            model_name='flete',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='flete',
            name='precio',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_de_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flete',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traslados.cliente'),
        ),
    ]
