# Generated by Django 5.1.4 on 2025-01-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0007_alter_categoria_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportista',
            name='flete',
        ),
        migrations.AddField(
            model_name='flete',
            name='cotizacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traslados.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
