# Generated by Django 5.1.4 on 2025-01-03 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0008_remove_transportista_flete_flete_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria de Paquete', 'verbose_name_plural': 'Categorias de Paquetes'},
        ),
        migrations.AddField(
            model_name='flete',
            name='transportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='traslados.transportista'),
        ),
    ]
