# Generated by Django 5.1.4 on 2025-01-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traslados', '0012_alter_transportista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportista',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
